// <auto-generated />
using System;
using AutoRegisterServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoRegisterServices.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoRegisterServices.Application.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastNmae");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("8eb13787-0273-4fa6-a21d-4be5ff0853e7"),
                            Age = (byte)26,
                            FirstName = "Sinjul",
                            LastNmae = "MSBH"
                        },
                        new
                        {
                            CustomerId = new Guid("94891122-ffb8-4d5b-96bc-d96e3d80d052"),
                            Age = (byte)26,
                            FirstName = "Jack",
                            LastNmae = "Slater"
                        });
                });

            modelBuilder.Entity("AutoRegisterServices.Application.Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastNmae");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("23734e12-1b8a-45b1-b131-ce8a7e0e2836"),
                            Age = (byte)26,
                            FirstName = "Sinjul",
                            LastNmae = "MSBH"
                        },
                        new
                        {
                            PersonId = new Guid("fada6115-01b9-4025-8cde-31c720cb7567"),
                            Age = (byte)26,
                            FirstName = "Jack",
                            LastNmae = "Slater"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
